swagger: '2.0'

info:
  title: Module pour rechercher dans tous les flux WFS Géoportail (Version Bêta)
  version: 1.0.1
  description: >

    Ce module permet d’intersecter toute couche WFS du géoportail exprimée dans le référentiel géographique WGS84 **EPSG:4326** avec la géométrie passée en paramètre.
    
    Un tri sémantique sur un attribut devra être fait en aval par l'application cliente.

    Note : les flux exprimés dans un référentiel autre que EPSG:4326 ne sont pas interrogeables via ce module actuellement

    Toutes les requêtes du module peuvent se faire en POST ou en GET. 

    Sur cette page, vous pouvez uniquement tester les modules avec des requêtes en GET.

    
    Consultez la [documentation utilisateur](https://apicarto.ign.fr/api/doc/pdf/docUser_moduleWfsGeoportail.pdf) pour plus d’informations sur les paramètres d’appel disponibles et le format des résultats.

    ## Clé WFS géoportail (apikey)
    
     Pour des raisons techniques le service demande toujours une clé dans le paramètre apikey. Il est recommandé d'utiliser les clés génériques dont la description est disponible sur [le site géoservices](https://geoservices.ign.fr/services-web-experts).
     Une prochaine évolution permettra de s'affranchir de cette contrainte.

    ## Couche source

      Les couches WFS disponibles sur le géoportail peuvent être listée via l’URL [https://wxs.ign.fr/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities](https://wxs.ign.fr/geoportail/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities) 

      Actuellement seules les couches exprimées dans le référentiel WGS84 (EPSG:4326) peuvent être utilisées. 
      Il est possible de vérifier le référentiel d’une couche en consultant la valeur de la balise `<DefaultCRS>`. 

      Valeur du référentiel géographique (CRS) des flux utilisables par le module : `<DefaultCRS>urn:ogc:def:crs:EPSG::4326</DefaultCRS>`
      
      Le nom technique de la couche source doit être utilisé. Celui-ci est indiqué par la balise `<Name>`.

      **Exemple pour le champ *source*** : CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle
      
      ## Géométrie

      La géometrie doit être exprimée en valeur décimale dans le référentiel WGS84

      **Exemples de géométrie** : (référentiel EPSG:4326)

      * Point :
        
         `{"type": "Point","coordinates":[-1.691634,48.104237]}`

      * MultiPolygon : 

         `{"type":"MultiPolygon","coordinates":[[[[-0.288863182067871,48.963666607295977],[-0.299592018127441,48.959299208576141],[-0.296330451965332,48.955325952385039],[-0.282125473022461,48.950675995388366],[-0.279722213745117,48.967019382922331],[-0.288863182067871,48.963666607295977]]]]}`
      
      * Polygone troué : 
      
         `{"type":"Polygon","coordinates":[[[1.2,48.85],[1.3,48.85],[1.3,48.9],[1.2,48.9],[1.2,48.85]],[[1.23,48.86],[1.23,48.88],[1.26,48.88],[1.26,48.86],[1.23,48.86]]]}`
      
      * Linéaire :

         `{"type":"LineString","coordinates":[[4.681549,47.793784],[4.741974,47.788248]]}`
      
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /wfs-geoportail/search:
    get:
      description: |
        Prend une geometrie de type GeoJSON en paramètre d'entrée et renvoie les informations intersectant cette géométrie
        Prend la source de donnée WFS Géoportail à interroger en paramètre d'entrée
      Paramètres de sorties : Retourne un résultat de Type "FeatureCollection"
      parameters:
        - name: apikey
          in: query
          description: Clé WFS géoportail
          type: string
          required: true
          
        - name: source
          in: query
          description: Source des données WFS Géoportail
          type: string
          required: true

        - name: geom
          in: query
          required: true
          schema:
            $ref: "#/definitions/Geometry"

        - name: _limit
          in: query
          description: Limite de résultats à afficher (chiffre entre 1 et 1000)
          type: integer
          required: false
          
        - name: _start
          in: query
          description: Position pour le début de la recherche
          type: integer
          required: false
      tags:
        - Geoportail
      responses:
        '200':
          description: "Succès"

definitions:          
          
# import definitions
  FeatureCollection:
    $ref: './schema/geojson.yml#definitions/FeatureCollection'
  Feature:
    $ref: './schema/geojson.yml#definitions/Feature'
  Geometry:
    $ref: './schema/geojson.yml#definitions/Geometry'
  MultiPolygon:
    $ref: './schema/geojson.yml#definitions/MultiPolygon'

  
