openapi: 3.0.0
info:
  title: payments
  version: '1.0'
servers:
  - url: 'http://api.mycompany.com/v1/payments/'
paths:
  /:
    post:
      summary: Pay for a booked trip
      tags:
        - Payments
      responses:
        '200':
          description: Successful payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  book_id:
                    type: string
                  cents:
                    type: string
                  status:
                    type: string
                  '':
                    type: string
      operationId: post-charges
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                book_id:
                  type: string
                payment_token:
                  type: string
                  description: Payment token generated by the payment gateway.
                cents:
                  type: string
      description: ''
    parameters: []
components:
  schemas: {}
