openapi: 3.0.0
info:
  title: trips/book
  version: '1.0'
servers:
  - url: 'http://api.mycompany.com/v1/trips'
paths:
  /books:
    post:
      summary: Book a trip
      tags: []
      responses:
        '200':
          description: Booked trip
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  trip_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum:
                      - booked
                      - canceled
                      - paid
      operationId: post-book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: string
                voucher_code:
                  type: string
      description: Book a trip.
    parameters: []
components:
  schemas: {}
