---
swagger: '2.0'
info:
  title: Hiboutik Rest API
  contact:
    name: Le Hibou
    url: https://demoapi.hiboutik.com/api/
  version: '2.0'
host: demoapi.hiboutik.com
basePath: "/api"
schemes:
- https
paths:
  "/action_links":
    get:
      tags:
      - action_links
      summary: Returns action links/buttons
      description: 'Returns action links/buttons<br />Scope for public applications
        : none'
      operationId: api.action_links.get
  "/action_links/":
    post:
      tags:
      - action_links
      summary: Add an action link/button
      description: Add an action link/button
      operationId: api.action_links.add
  "/action_link_exec/":
    post:
      tags:
      - action_links
      summary: Execute an action link/button. If the action_link_type is 0 (embeded)
        the action_link_url is triggered else action_link_url is returned
      description: Execute an action link/button
      operationId: api.action_links.exec
  "/action_links/{action_link_id}":
    delete:
      tags:
      - action_links
      summary: Delete action_link_id
      description: Delete action_link_id.
      operationId: api.action_links.delete
  "/brands":
    get:
      tags:
      - brands
      summary: Returns brands by ID
      description: 'Returns brands by ID (ORDER BY brand_id DESC)<br />Scope for public
        applications : read_products<br />Results per page : 250'
      operationId: api.brands.index
    put:
      tags:
      - brands
      summary: Update a brand
      description: 'Update a brand<br />Scope for public applications : write_products'
      operationId: api.brands.update
    post:
      tags:
      - brands
      summary: Create a new brand
      description: 'Create a new brand<br />Scope for public applications : write_products'
      operationId: api.brands.add
  "/calendar/events/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - calendar
      summary: Returns calendar events for store_id for a specific day
      description: 'Returns calendar events for store_id for a specific day<br />Scope
        for public applications : read_calendar_events'
      operationId: api.calendar.index
  "/calendar/event/{event_id}":
    get:
      tags:
      - calendar
      summary: Returns calendar event_id
      description: 'Returns calendar event_id<br />Scope for public applications :
        read_calendar_events'
      operationId: api.calendar.event_id.index
  "/calendar/events/":
    post:
      tags:
      - calendar
      summary: Add a calendar event
      description: 'Add a calendar event<br />Scope for public applications : write_calendar_events'
      operationId: api.calendar.add_event
  "/calendar/events/{id}/":
    delete:
      tags:
      - calendar
      summary: Delete a calendar event
      description: 'Delete a calendar event<br />Scope for public applications : write_calendar_events'
      operationId: api.calendar.delete_event
  "/categories":
    get:
      tags:
      - categories
      summary: Returns categories by ID
      description: 'Returns categories by ID (ORDER BY category_id DESC)<br />Scope
        for public applications : read_products<br />Results per page : 250'
      operationId: api.categories.index
    put:
      tags:
      - categories
      summary: Update a category
      description: 'Update a category<br />Scope for public applications : write_products'
      operationId: api.categories.update
    post:
      tags:
      - categories
      summary: Create a new category
      description: 'Create a new category<br />Scope for public applications : write_products'
      operationId: api.categories.add
  "/credit_notes/{store_id}":
    get:
      tags:
      - credit notes
      summary: Returns pending credit notes in a store_id
      description: 'Returns pending credit notes in a store_id<br />Scope for public
        applications : read_reports<br />Results per page : 250'
      operationId: api.credit_notes.index
  "/customers/":
    get:
      tags:
      - customers
      summary: Returns customers by ID
      description: 'Returns customers by ID (ORDER BY customers_id DESC)<br />Scope
        for public applications : read_customers<br />Results per page : 250'
      operationId: api.customers.index
    post:
      tags:
      - customers
      summary: Create a new customer
      description: 'Create a new customer<br />Scope for public applications : write_customers'
      operationId: api.customers.add
  "/customers_birthday/{month}/{day}":
    get:
      tags:
      - customers
      summary: Returns customers born on a specific day
      description: 'Returns customers born on a specific day<br />Scope for public
        applications : read_customers'
      operationId: api.customers_birthday.index
  "/customers/lists/":
    get:
      tags:
      - customers
      summary: Returns customers lists by ID
      description: 'Returns customers lists (ORDER BY list_id DESC)<br />Scope for
        public applications : read_customers<br />Results per page : 250'
      operationId: api.customers_lists.index
  "/customers/lists/{list_id}":
    get:
      tags:
      - customers
      summary: Returns customers from a specific list
      description: 'Returns customers from a specific list<br />Scope for public applications
        : read_customers<br />Results per page : 250'
      operationId: api.customers_lists.list_id.search
  "/number_of_customers":
    post:
      tags:
      - customers
      summary: Set number of customers in shop_id at date
      description: 'Set number of customers in shop_id at date<br />Scope for public
        applications : write_reports'
      operationId: api.customers.set_number
  "/customers_addresses/{address_id}":
    get:
      tags:
      - customers
      summary: Returns details of a customer address
      description: 'Returns details of a customer address<br />Scope for public applications
        : read_customers'
      operationId: api.customers_addresses.address_id
    delete:
      tags:
      - customers
      summary: Delete a customer address
      description: 'Delete a customer address<br />Scope for public applications :
        write_customers'
      operationId: api.customers_addresses.delete
  "/customers_addresses":
    post:
      tags:
      - customers
      summary: Add a customer address
      description: 'Add a customer address<br />Scope for public applications : write_customers'
      operationId: api.customers_addresses.add
  "/customers_addresses/{address_id}/":
    put:
      tags:
      - customers
      summary: Update a customer address
      description: 'Update a customer address<br />Scope for public applications :
        write_customers'
      operationId: api.customers_addresses.update
  "/customer/{customers_id}":
    get:
      tags:
      - customers
      summary: Returns details of a customers_id
      description: 'Returns details of a customers_id<br />Scope for public applications
        : read_customers'
      operationId: api.customer.customers_id
    delete:
      tags:
      - customers
      summary: Delete a customer
      description: 'Delete a customer<br />Scope for public applications : write_customers'
      operationId: api.customer.delete
  "/customer/{customers_id}/products_solds/":
    get:
      tags:
      - customers
      summary: Returns products sold to a specific customers_id
      description: 'Returns products sold to a specific customers_id (ORDER BY date_z
        DESC)<br />Scope for public applications : read_customers<br />Results per
        page : 250'
      operationId: api.customer.customers_id.products_solds
  "/customer/{customers_id}/":
    put:
      tags:
      - customers
      summary: Update a customer
      description: 'Update a customer<br />Scope for public applications : write_customers'
      operationId: api.customer.update
  "/customers_credit/{customers_id}":
    get:
      tags:
      - customers_credit
      summary: Returns store credit lines for a customers_id
      description: 'Returns store credit lines for a customers_id<br />Scope for public
        applications : read_store_credit<br />Results per page : 250'
      operationId: api.customers_credit.customers_id
  "/customers_credit/":
    post:
      tags:
      - customers_credit
      summary: Add a store credit line to a customers_id
      description: 'Add a store credit line to a customers_id<br />Scope for public
        applications : write_store_credit'
      operationId: api.customers_credit.add_line
  "/tags/customers/":
    get:
      tags:
      - customers
      - tags
      summary: Returns tags for customers
      description: 'Returns tags for customers<br />Scope for public applications
        : read_customers'
      operationId: api.tags.customers
  "/customers_tags/{customer_id}":
    get:
      tags:
      - customers
      - tags
      summary: Returns tags for a specific customer_id
      description: 'Returns tags for a specific customer_id<br />Scope for public
        applications : read_customers'
      operationId: api.tags.customer_id
    post:
      tags:
      - customers
      - tags
      summary: Add a tag to a specific customer_id
      description: 'Add a tag to a specific customer_id<br />Scope for public applications
        : write_customers'
      operationId: api.customers_tags.add
  "/customers_tags/{customer_id}/{tag_id}":
    delete:
      tags:
      - customers
      - tags
      summary: Delete a tag to a specific customer_id
      description: 'Delete a tag to a specific customer_id<br />Scope for public applications
        : write_customers'
      operationId: api.customers_tags.delete
  "/inventory_inputs/":
    get:
      tags:
      - products
      - inventory_inputs
      summary: Returns the list of stock orders
      description: 'Returns the list of stock orders<br />Scope for public applications
        : read_inventory<br />Results per page : 250'
      operationId: api.inventory_inputs.index
    post:
      tags:
      - products
      - inventory_inputs
      summary: Create a stock order
      description: 'Create a stock order<br />Scope for public applications : write_inventory'
      operationId: api.inventory_inputs.add
  "/inventory_inputs/{inventory_input_id}":
    get:
      tags:
      - products
      - inventory_inputs
      summary: Returns details of a stock order
      description: 'Returns details of a stock order<br />Scope for public applications
        : read_inventory'
      operationId: api.inventory_inputs_info.index
  "/inventory_input_details/{inventory_input_id}":
    get:
      tags:
      - products
      - inventory_inputs
      summary: Returns details for a stock order
      description: 'Returns details for a stock order<br />Scope for public applications
        : read_inventory'
      operationId: api.inventory_input_details.index
    post:
      tags:
      - products
      - inventory_inputs
      summary: Add a product line to a stock order
      description: 'Add a product line to a stock order<br />Scope for public applications
        : write_inventory'
      operationId: api.inventory_input_details.add_product
  "/inventory_input_details/{inventory_input_detail_id}/":
    put:
      tags:
      - products
      - inventory_inputs
      summary: Update an inventory_input_detail_id
      description: 'Update an inventory_input_detail_id<br />Scope for public applications
        : write_inventory'
      operationId: api.inventory_input_detail_id.update
  "/inventory_input_validate/":
    post:
      tags:
      - products
      - inventory_inputs
      summary: Validate a stock order
      description: 'Validate a stock order<br />Scope for public applications : write_inventory'
      operationId: api.inventory_input.validate
  "/inventory_inputs_on_hold/":
    get:
      tags:
      - products
      - inventory_inputs
      summary: Returns the list of stock orders details on hold
      description: 'Returns the list of stock orders details on hold<br />Scope for
        public applications : read_inventory<br />Results per page : 250'
      operationId: api.inventory_inputs_on_hold.index
  "/kitchen/open_tables":
    get:
      tags:
      - kitchen
      summary: Returns pending sales sent to kitchen
      description: 'Returns pending sales sent to kitchen<br />Scope for public applications
        : read_kitchen_screen'
      operationId: api.kitchen.open_tables
  "/kitchen/cooking_stations":
    get:
      tags:
      - kitchen
      summary: Returns cooking stations
      description: 'Returns cooking stations<br />Scope for public applications :
        read_kitchen_screen'
      operationId: api.kitchen.cooking_stations
  "/kitchen/sales/{sale_id}":
    get:
      tags:
      - kitchen
      summary: Returns sale details
      description: 'Returns sale details<br />Scope for public applications : read_kitchen_screen'
      operationId: api.kitchen.sale_details
  "/kitchen/line_item":
    post:
      tags:
      - kitchen
      summary: Add item to the kitchen screen
      description: 'Add item to the kitchen screen<br />Scope for public applications
        : write_kitchen_screen'
      operationId: api.kitchen.add_line_item
  "/kitchen/line_items":
    post:
      tags:
      - kitchen
      summary: Add sale items to the kitchen screen
      description: 'Add item to the kitchen screen<br />Scope for public applications
        : write_kitchen_screen'
      operationId: api.kitchen.add_line_items
  "/kitchen/item_status":
    post:
      tags:
      - kitchen
      summary: Update item status
      description: 'Update item status<br />Scope for public applications : write_kitchen_screen'
      operationId: api.kitchen.update_item_status
  "/kitchen/sales/{sale_id}/":
    delete:
      tags:
      - kitchen
      summary: Delete a sale from the kitchen screen
      description: 'Delete a sale from the kitchen screen<br />Scope for public applications
        : write_kitchen_screen'
      operationId: api.kitchen.delete_sale
  "/message/":
    post:
      tags:
      - message
      summary: Post a new message
      description: Post a new message
      operationId: api.message.add
  "/modifiers/":
    get:
      tags:
      - modifiers
      summary: Returns the list of modifiers
      description: 'Returns modifiers<br />Scope for public applications : read_products'
      operationId: api.modifiers.index
    post:
      tags:
      - modifiers
      summary: Create a modifier
      description: 'Create a modifier<br />Scope for public applications : write_products'
      operationId: api.modifiers.add
  "/modifiers/{modifier_id}/":
    put:
      tags:
      - modifiers
      summary: Update a modifier
      description: 'Update a modifier<br />Scope for public applications : write_products'
      operationId: api.modifiers.update
  "/payment_types/{store_id}/":
    get:
      tags:
      - payments
      summary: Returns payment types for store_id
      description: 'Returns payment types for store_id<br />Scope for public applications
        : read_settings'
      operationId: api.payment_types.index
  "/payments/due_date/{store_id}/":
    get:
      tags:
      - payments
      summary: Returns the list of payments with due dates for a specific store_id
      description: 'Returns the list of payments with due dates for a specific store_id<br
        />Scope for public applications : read_sales<br />Results per page : 250'
      operationId: api.payments_due_date.index
  "/prepaid_purchases/":
    get:
      tags:
      - prepaid_purchases
      summary: Returns prepaid purchases lines
      description: 'Returns prepaid purchases lines<br />Scope for public applications
        : read_customers<br />Results per page : 250'
      operationId: api.prepaid_purchases.index
    post:
      tags:
      - prepaid_purchases
      summary: Add a prepaid purchase line to a customers_id
      description: 'Add a prepaid purchase line to a customers_id<br />Scope for public
        applications : write_customers'
      operationId: api.prepaid_purchases.add_line
  "/prepaid_purchases/{customers_id}":
    get:
      tags:
      - prepaid_purchases
      summary: Returns prepaid purchases lines for a customers_id
      description: 'Returns prepaid purchases lines for a customers_id<br />Scope
        for public applications : read_customers<br />Results per page : 250'
      operationId: api.prepaid_purchases.customers_id
  "/print/misc/":
    post:
      tags:
      - print
      summary: Print a document
      description: 'Print a document<br />Scope for public applications : print<br
        /><br />In order to be able to print with this method you need to :<br />-
        On Hiboutik in ''General Settings'' set the public IP address of your point
        of sale. You can use a DYN DNS service if you don''t have a public static
        IP address. <br />- Set a port forwarding on you router from the port of your
        choice (the one you will fill below) to the port 9100 on your local printer'
      operationId: api.print.misc
  "/products/":
    get:
      tags:
      - products
      summary: Returns products by ID
      description: 'Returns products (default sorting is by ID DESC)<br />Scope for
        public applications : read_products<br />Results per page : 250'
      operationId: api.products.index
    post:
      tags:
      - products
      summary: Create a new product
      description: 'Create a new product<br />Scope for public applications : write_products'
      operationId: api.products.add
  "/products_images/{product_id}/":
    post:
      tags:
      - products
      summary: Add a product image
      description: 'Add a product image<br />Scope for public applications : write_products'
      operationId: api.products_images.add
  "/products_images_1000x1000/{product_id}/":
    post:
      tags:
      - products
      summary: Add a product image
      description: 'Add a product image<br />Scope for public applications : write_products'
      operationId: api.products_images_1000x1000.add
  "/products_barcode/{store_id}/{product_id}/{size_id}/":
    get:
      tags:
      - products
      summary: Returns product barcode for a store_id & product_id & size_id
      description: 'Returns product barcode for a store_id & product_id & size_id<br
        />Scope for public applications : read_products'
      operationId: api.products_barcode.index
  "/products_sold/{store_id}/{year}/{month}/{day}/":
    get:
      tags:
      - products
      - sales
      summary: Returns products sold in a store_id at a specific date
      description: 'Returns products sold in a store_id at a specific date<br />Scope
        for public applications : read_reports<br />Results per page : 250'
      operationId: api.products_sold.index
  "/products_purchased/{warehouse_id}/{year}/{month}/{day}/":
    get:
      tags:
      - products
      - inventory_inputs
      summary: Returns products purchased in a warehouse_id at a specific date
      description: 'Returns products purchased in a warehouse_id at a specific date<br
        />Scope for public applications : read_reports<br />Results per page : 250'
      operationId: api.products_purchased.index
  "/products_returned/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - reports
      summary: Returns product returned for store_id for a specific day
      description: 'Returns product returned for store_id for a specific day<br />Scope
        for public applications : read_reports<br />Results per page : 250'
      operationId: api.products_returned.index
  "/product/{product_id}/":
    put:
      tags:
      - products
      summary: Update a product
      description: 'Update a product<br />Scope for public applications : write_products'
      operationId: api.product.update
  "/products/{product_id}":
    get:
      tags:
      - products
      summary: Returns product details
      description: 'Returns product details<br />Scope for public applications : read_products'
      operationId: api.products.id
  "/products/search/name/{q}":
    get:
      tags:
      - products
      - search
      summary: Returns products search results by name
      description: 'Returns products search results by name<br />Scope for public
        applications : read_products<br />Results per page : 250'
      operationId: api.products.name.search
  "/products/search/barcode/{q}/":
    get:
      tags:
      - products
      - search
      summary: Returns products search results by barcode
      description: 'Returns products search results by barcode<br />Scope for public
        applications : read_products'
      operationId: api.products.barcode.search
  "/products/search/supplier_reference/{q}/":
    get:
      tags:
      - products
      - search
      summary: Returns products search results by supplier reference
      description: 'Returns products search results by supplier reference<br />Scope
        for public applications : read_products'
      operationId: api.products.supplier_reference.search
  "/products/search/category/{category_id}":
    get:
      tags:
      - products
      - categories
      - search
      summary: Returns products search results by category_id
      description: 'Returns products search results by category_id<br />Scope for
        public applications : read_products<br />Results per page : 250'
      operationId: api.products.category_id.search
  "/products/search/taxes/{tax_id}":
    get:
      tags:
      - products
      - taxes
      - search
      summary: Returns products search results by tax_id
      description: 'Returns products search results by tax_id<br />Scope for public
        applications : read_products<br />Results per page : 250'
      operationId: api.products.tax_id.search
  "/products/search/tags/{tag_id}":
    get:
      tags:
      - products
      - search
      summary: Returns products search results by tag_id
      description: 'Returns products search results by tag_id<br />Scope for public
        applications : read_products<br />Results per page : 250'
      operationId: api.products.tag_id.search
  "/products/search/open_packages":
    get:
      tags:
      - products
      - search
      summary: Returns open package products
      description: 'Returns open package products<br />Scope for public applications
        : read_products<br />Results per page : 250'
      operationId: api.products.open_packages.search
  "/product_specific_rules/{shop_id}/{product_id}/{size_id}":
    delete:
      tags:
      - products
      summary: Delete a product specific rule
      description: 'Delete a product specific rule<br />Scope for public applications
        : write_products'
      operationId: api.product_specific_rules.delete
  "/products_modifiers/{product_id}":
    get:
      tags:
      - products
      - modifiers
      summary: Returns modifiers for a specific product_id
      description: 'Returns modifiers for a specific product_id<br />Scope for public
        applications : read_products'
      operationId: api.modifiers.product_id
    post:
      tags:
      - products
      - modifiers
      summary: Add a modifier to a specific product_id
      description: 'Add a modifier to a specific product_id<br />Scope for public
        applications : write_products'
      operationId: api.products_modifiers.add
  "/products_modifiers/":
    get:
      tags:
      - products
      - modifiers
      summary: Returns modifiers for products
      description: 'Returns modifiers products<br />Scope for public applications
        : read_products'
      operationId: api.modifiers.products.index
  "/products_modifiers/{product_id}/{modifier_id}":
    delete:
      tags:
      - products
      - modifiers
      summary: Delete a modifier to a specific product_id
      description: 'Delete a modifier to a specific product_id<br />Scope for public
        applications : write_products'
      operationId: api.products_modifiers.delete
  "/tags/products/":
    get:
      tags:
      - products
      - tags
      summary: Returns tags for products
      description: 'Returns tags for products<br />Scope for public applications :
        read_products'
      operationId: api.tags.products
  "/products_tags/{product_id}":
    get:
      tags:
      - products
      - tags
      summary: Returns tags for a specific product_id
      description: 'Returns tags for a specific product_id<br />Scope for public applications
        : read_products'
      operationId: api.tags.product_id
    post:
      tags:
      - products
      - tags
      summary: Add a tag to a specific product_id
      description: 'Add a tag to a specific product_id<br />Scope for public applications
        : write_products'
      operationId: api.products_tags.add
  "/products_tags/":
    get:
      tags:
      - products
      - tags
      summary: Returns tags products
      description: 'Returns tags for products<br />Scope for public applications :
        read_products'
      operationId: api.tags.products.index
  "/products_tags/{product_id}/{tag_id}":
    delete:
      tags:
      - products
      - tags
      summary: Delete a tag to a specific product_id
      description: 'Delete a tag to a specific product_id<br />Scope for public applications
        : write_products'
      operationId: api.products_tags.delete
  "/reset/":
    post:
      tags:
      - reset
      summary: Reset account
      description: 'Reset account<br />Scope for public applications : write_settings<br
        />Account must be in demo mode'
      operationId: api.reset.misc
  "/reset/customers/loyalty_points":
    post:
      tags:
      - reset
      summary: Reset customers loyalty points
      description: 'Reset loyalty points for customers_id<br />Scope for public applications
        : write_settings<br />Account must be in demo mode'
      operationId: api.reset.customers.misc
  "/rooms/":
    get:
      tags:
      - ressources
      summary: Returns rooms by ID
      description: Returns rooms by ID
      operationId: api.rooms.index
  "/ressources/":
    get:
      tags:
      - ressources
      summary: Returns ressources by ID
      description: Returns ressources by ID
      operationId: api.ressources.index
  "/ressources/{ressource_id}/":
    get:
      tags:
      - ressources
      summary: Returns ressource details
      description: Returns ressource details
      operationId: api.ressources.id
  "/sales/comments/":
    post:
      tags:
      - sales
      summary: Add/Update comments
      description: 'Add/Update comments<br />Scope for public applications : write_sales'
      operationId: api.sales.comments.add
  "/sales/":
    post:
      tags:
      - sales
      summary: Create a new sale
      description: 'Create a new sale<br />Scope for public applications : write_sales'
      operationId: api.sales.add
  "/sales/add_product/":
    post:
      tags:
      - sales
      summary: Add a product on a sale
      description: 'Add a product on a sale<br />Scope for public applications : write_sales'
      operationId: api.sales.add_product
  "/sales/add_credit_note/":
    post:
      tags:
      - sales
      summary: Add a credit note on a sale
      description: 'Add a credit note on a sale<br />Scope for public applications
        : write_sales'
      operationId: api.sales.add_credit_note
  "/sales/close/":
    post:
      tags:
      - sales
      summary: Close a sale
      description: 'Close a sale<br />Scope for public applications : write_sales'
      operationId: api.sales.close
  "/sales_payment_div/":
    post:
      tags:
      - sales
      summary: Add a DIV payment to a sale
      description: 'Add a DIV payment to a sale<br />Scope for public applications
        : write_sales'
      operationId: api.sales.payment_div
  "/sales_payment_div/{payment_detail_id}/":
    put:
      tags:
      - sales
      summary: Update a DIV payment
      description: 'Update a DIV payment<br />Scope for public applications : write_sales'
      operationId: api.sale.payment_div.update
  "/sales_payment_div/{payment_detail_id}":
    delete:
      tags:
      - sales
      summary: Delete DIV payment
      description: 'Delete DIV payment<br />Scope for public applications : write_sales'
      operationId: api.sales.payment_div.delete
  "/sale/{sale_id}/":
    put:
      tags:
      - sales
      summary: Update a sale attribute
      description: 'Update a sale attribute<br />Scope for public applications : write_sales'
      operationId: api.sale.update
  "/sale/{sale_id}":
    delete:
      tags:
      - sales
      summary: Delete sale
      description: 'Delete sale. Sale must be empty and should not have any CREDIT
        like payments.<br />Scope for public applications : write_sales'
      operationId: api.sales.delete
  "/sale_line_item/{line_item_id}":
    get:
      tags:
      - sales
      summary: Returns details of a line_item_id
      description: 'Returns details of a line_item_id<br />Scope for public applications
        : read_sales'
      operationId: api.sales.line_item_id
    delete:
      tags:
      - sales
      summary: Delete line_item
      description: 'Delete line_item<br />Scope for public applications : write_sales'
      operationId: api.sale_line_item.delete
  "/sale_line_item/{line_item_id}/":
    put:
      tags:
      - sales
      summary: Update a line_item attribute
      description: 'Update a line_item attribute<br />Scope for public applications
        : write_sales'
      operationId: api.sale_line_item.update
  "/sales/{sale_id}":
    get:
      tags:
      - sales
      summary: Returns details of a sale
      description: 'Returns details of a sale<br />Scope for public applications :
        read_sales'
      operationId: api.sales.sale_id
  "/closed_sales/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - sales
      summary: Returns closed sales in a store_id for a specific day or month
      description: 'Returns closed sales in a store_id for a specific day or month<br
        />Scope for public applications : read_reports<br />Results per page : 250'
      operationId: api.closed_sales.index
  "/closed_sales_by_tag/{tag_id}/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - sales
      summary: Returns closed sales for a specific tag_id in a store_id for a specific
        day or month
      description: 'Returns closed sales for a specific tag_id in a store_id for a
        specific day or month<br />Scope for public applications : read_reports<br
        />Results per page : 250'
      operationId: api.closed_sales_by_tag.index
  "/open_sales/{store_id}":
    get:
      tags:
      - sales
      summary: Returns open sales in a store_id
      description: 'Returns open sales in a store_id (ORDER BY sale_id DESC)<br />Scope
        for public applications : read_reports<br />Results per page : 250'
      operationId: api.open_sales.index
  "/sale_line_item_modifier/{line_item_id}/{modifier_id}/":
    post:
      tags:
      - sales
      summary: Add a modifier to a line_item
      description: 'Add a modifier to a line_item<br />Scope for public applications
        : write_sales'
      operationId: api.sale_line_item_modifier.add
    delete:
      tags:
      - sales
      summary: Delete a modifier on a line_item
      description: 'Delete a modifier on a line_item<br />Scope for public applications
        : write_sales'
      operationId: api.sale_line_item_modifier.delete
  "/sale_line_item_exchange/{line_item_id}/{stock_id}/":
    put:
      tags:
      - sales
      summary: Exchange a line_item
      description: 'Exchange a line_item<br />Scope for public applications : write_sales'
      operationId: api.sale_line_item.exchange
  "/sales/add_global_discount/":
    post:
      tags:
      - sales
      summary: Global discount
      description: 'Global discount<br />Scope for public applications : write_sales'
      operationId: api.add_global_discount
  "/sales/open_package/":
    post:
      tags:
      - sales
      - package
      summary: Add an open package on a sale
      description: 'Add an open package on a sale<br />Scope for public applications
        : write_sales'
      operationId: api.sales.add_open_package
  "/sales/open_package/pack/{pack_line_item_id}/{product_line_item_id}":
    put:
      tags:
      - sales
      - package
      summary: Pack a product in an open package
      description: 'Pack a product in an open package<br />Scope for public applications
        : write_sales'
      operationId: api.open_package.pack
  "/sales/open_package/unpack/{line_item_id}":
    put:
      tags:
      - sales
      - package
      summary: Unpack a line item id (either a product or an open package)
      description: 'Unpack a line item id (either a product or an open package)<br
        />Scope for public applications : write_sales'
      operationId: api.open_package.unpack
  "/sales/open_package/{line_item_id}":
    delete:
      tags:
      - sales
      - package
      summary: Delete an open package (must be completely unpacked)
      description: 'Delete an open package (must be completely unpacked)<br />Scope
        for public applications : write_sales'
      operationId: api.open_package.delete
  "/tags/sales/":
    get:
      tags:
      - sales
      - tags
      summary: Returns tags for sales
      description: 'Returns tags for sales<br />Scope for public applications : read_sales'
      operationId: api.tags.sales
  "/sales_tags/{sale_id}":
    get:
      tags:
      - sales
      - tags
      summary: Returns tags for a specific sale_id
      description: 'Returns tags for a specific sale_id<br />Scope for public applications
        : read_sales'
      operationId: api.tags.sale_id
    post:
      tags:
      - sales
      - tags
      summary: Add a tag to a specific sale_id
      description: 'Add a tag to a specific sale_id<br />Scope for public applications
        : write_sales'
      operationId: api.sales_tags.add
  "/sales_tags/{sale_id}/{tag_id}":
    delete:
      tags:
      - sales
      - tags
      summary: Delete a tag to a specific sale_id
      description: 'Delete a tag to a specific sale_id<br />Scope for public applications
        : write_sales'
      operationId: api.sales_tags.delete
  "/customers/search/":
    get:
      tags:
      - customers
      - search
      summary: Search for customers that match a supplied query
      description: 'Search for customers that match a supplied query<br />Scope for
        public applications : read_customers<br />Results per page : 250'
      operationId: api.search.customers.index
  "/customers/search/tags/{tag_id}":
    get:
      tags:
      - customers
      - search
      summary: Returns customers search results by tag_id
      description: 'Returns customers search results by tag_id<br />Scope for public
        applications : read_customers<br />Results per page : 250'
      operationId: api.customers.tag_id.search
  "/stock_transfer/search/":
    get:
      tags:
      - stock_transfer
      - search
      summary: Search for stock_transfer that match a supplied query
      description: 'Search for stock_transfer that match a supplied query<br />Scope
        for public applications : read_inventory<br />Results per page : 250'
      operationId: api.search.stock_transfer.index
  "/products/search/":
    get:
      tags:
      - products
      - search
      summary: Search for products that match a supplied query
      description: 'Search for products that match a supplied query<br />Scope for
        public applications : read_products<br />Results per page : 250'
      operationId: api.search.products.index
  "/sales/search/ext_ref/{q}":
    get:
      tags:
      - sales
      - search
      summary: Returns sales search results by ext_ref
      description: 'Returns sales search results by ext_ref<br />Scope for public
        applications : read_sales<br />Results per page : 250'
      operationId: api.sales.ext_ref.search
  "/shoutbox/":
    post:
      tags:
      - shoutbox
      summary: Post a new message
      description: 'Post a new message<br />Scope for public applications : read_customers'
      operationId: api.shoutbox.add
  "/sizes/{size_type_id}":
    get:
      tags:
      - sizes
      summary: Returns variants for a specific variant type ID
      description: 'Returns variants for a specific variant type ID<br />Scope for
        public applications : read_products'
      operationId: api.sizes.stock_id
  "/sizes/":
    post:
      tags:
      - sizes
      summary: Create a new size
      description: 'Create a new size<br />Scope for public applications : write_products'
      operationId: api.sizes.add
  "/size_types":
    get:
      tags:
      - sizes
      summary: Returns variant types by ID
      description: 'Returns variant types by ID<br />Scope for public applications
        : read_products'
      operationId: api.size_types.id
  "/size_types/":
    post:
      tags:
      - sizes
      summary: Create a new size type
      description: 'Create a new size type<br />Scope for public applications : write_products'
      operationId: api.size_types.add
  "/sizes_pretty/":
    get:
      tags:
      - sizes
      summary: Returns variants types by ID - Pretty
      description: 'Returns variant types by ID - Pretty<br />Scope for public applications
        : read_products'
      operationId: api.sizes_pretty.stock_id
  "/sizes_specific_rules":
    get:
      tags:
      - sizes
      summary: Returns specific rules for sizes
      description: 'Returns specific rules for sizes<br />Scope for public applications
        : read_products<br />Results per page : 250'
      operationId: api.sizes_specific_rules.id
  "/reports/turnover/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - reports
      summary: Returns sales total for store_id for a specific day or month
      description: 'Returns sales total for store_id for a specific day or month <br
        />Scope for public applications : read_reports<br />Results per page : 250'
      operationId: api.stats.turnover.index
  "/reports/product/{product_id}/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - reports
      summary: Returns sales for a specific product id
      description: 'Returns sales for a specific product id<br />Scope for public
        applications : read_reports<br />Results per page : 250'
      operationId: api.stats.product.index
  "/reports/products_tags/{store_id}/{year}/{month}":
    get:
      tags:
      - reports
      summary: Returns sales for a specific product id
      description: 'Returns sales total for store_id for a specific month by products
        tags<br />Scope for public applications : read_reports<br />Results per page
        : 250'
      operationId: api.stats.products_tags.index
  "/reports/sales_by_tag/{tag_id}/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - reports
      summary: Returns sales for a specific tag_id id
      description: 'Returns sales for a specific tag_id<br />Scope for public applications
        : read_reports<br />Results per page : 250<br />The only mandatoty parameter
        is store_id'
      operationId: api.stats.sales_by_tag.index
  "/reports/products/{store_id}/{year}/{month}":
    get:
      tags:
      - reports
      summary: Returns product sold for store_id for a specific month
      description: 'Returns product sold for store_id for a specific month<br />Scope
        for public applications : read_reports<br />Results per page : 250'
      operationId: api.stats.products.index
  "/reports/categories/{store_id}/{year}/{month}":
    get:
      tags:
      - reports
      summary: Returns sales by category for store_id for a specific month
      description: 'Returns sales by category for store_id for a specific month <br
        />Scope for public applications : read_reports<br />Results per page : 250'
      operationId: api.stats.categories.index
  "/reports/brands/{store_id}/{year}/{month}":
    get:
      tags:
      - reports
      summary: Returns sales by brand for store_id for a specific month
      description: 'Returns sales by brand for store_id for a specific month<br />Scope
        for public applications : read_reports<br />Results per page : 250'
      operationId: api.stats.brands.index
  "/reports/suppliers/{store_id}/{year}/{month}":
    get:
      tags:
      - reports
      summary: Returns sales by supplier for store_id for a specific month
      description: 'Returns sales by supplier for store_id for a specific month<br
        />Scope for public applications : read_reports<br />Results per page : 250'
      operationId: api.stats.suppliers.index
  "/reports/sales_per_customer/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - reports
      summary: Returns number of sales by customer for store_id for a specific day
        or month
      description: 'Returns number of sales by customer for store_id for a specific
        day or month<br />Scope for public applications : read_reports<br />Results
        per page : 250'
      operationId: api.stats.sales_per_customer.index
  "/reports/refresh/supply_prices":
    get:
      tags:
      - reports
      summary: Refresh supply prices of sold products based on a First In First Out
        (FIFO) calculation method
      description: 'Refresh supply prices of sold products based on a First In First
        Out (FIFO) calculation method<br />Scope for public applications : read_reports'
      operationId: api.stats.refresh_supply_prices
  "/reports/refresh/customers":
    get:
      tags:
      - reports
      summary: Refresh customers data (last order date, turnover, loyalty points etc...)
      description: 'Refresh customers data (last order date, turnover, loyalty points
        etc...)<br />Scope for public applications : read_reports'
      operationId: api.stats.refresh_customers
  "/reports/refresh/stats/{year}/{month}":
    get:
      tags:
      - reports
      summary: Refresh stats
      description: 'Refresh stats<br />Scope for public applications : read_reports'
      operationId: api.stats.refresh_stats
  "/stock_available/warehouse_id/{warehouse_id}":
    get:
      tags:
      - stock
      - warehouses
      summary: Returns stock available for a specific warehouse_id
      description: 'Returns stock available for a specific warehouse_id<br />Scope
        for public applications : read_inventory'
      operationId: api.stock_available.stock_id
  "/stock_available/all_wh":
    get:
      tags:
      - stock
      - warehouses
      summary: Returns stock available for all warehouses
      description: 'Returns stock available for all warehouses<br />Scope for public
        applications : read_inventory'
      operationId: api.stock_available.all_wh
  "/stock_available/product_id/{product_id}":
    get:
      tags:
      - stock
      - products
      summary: Returns stock available for a specific product_id
      description: 'Returns stock available for a specific product_id<br />Scope for
        public applications : read_inventory'
      operationId: api.stock_available.product_id
  "/stock_available/product_id_size/{product_id}/{product_size}":
    get:
      tags:
      - stock
      - products
      summary: Returns stock available for a specific product_id and size_id
      description: 'Returns stock available for a specific product_id and size_id<br
        />Scope for public applications : read_inventory'
      operationId: api.stock_available.product_id_size
  "/stock_available/sn/{product_id}/{product_size}":
    get:
      tags:
      - stock
      - products
      summary: Returns serial numbers available for a specific product_id and size_id
      description: 'Returns serial numbers available for a specific product_id and
        size_id<br />Scope for public applications : read_inventory<br />Results per
        page : 250'
      operationId: api.stock_available.by_sn
  "/stock_alert/":
    put:
      tags:
      - stock
      - products
      summary: Set product stock alert
      description: 'Set product stock alert<br />Scope for public applications : write_inventory'
      operationId: api.stock_available.set_alert
  "/reset_stock_alerts/":
    get:
      tags:
      - stock
      - products
      summary: Reset stock alerts for all products for all warehouses
      description: 'Reset stock alerts for all products for all warehouses<br />Scope
        for public applications : write_inventory'
      operationId: api.stock_available.reset_stock_alert
  "/inventory_inputs/warehouse_id/{warehouse_id}":
    get:
      tags:
      - stock
      - warehouses
      summary: Returns stock orders for a specific warehouse_i
      description: 'Returns stock orders for a specific warehouse_i<br />Scope for
        public applications : read_inventory<br />Results per page : 250'
      operationId: api.inventory_inputs.warehouse_id
  "/inventory_counts/":
    post:
      tags:
      - inventory_counts
      summary: Set/Modify a counted quantity for a product
      description: 'Set/Modify a counted quantity for a product<br />Scope for public
        applications : write_inventory'
      operationId: api.inventory_counts.add
  "/inventory_close/":
    post:
      tags:
      - inventory_counts
      summary: Close an inventory count (stock-take)
      description: 'Close an inventory count (stock-take)<br />Scope for public applications
        : write_inventory'
      operationId: api.inventory_counts.close
  "/inventory_counts/sales/{warehouse_id}/{year}/{month}":
    get:
      tags:
      - inventory_counts
      summary: Returns sales linked to inventory counts for a specific month
      description: 'Returns sales linked to inventory counts for a specific month<br
        />Scope for public applications : read_inventory'
      operationId: api.inventory_counts.sales.index
  "/inventory_counts/stock_orders/{warehouse_id}/{year}/{month}":
    get:
      tags:
      - inventory_counts
      summary: Returns stock orders linked to inventory counts for a specific month
      description: 'Returns stock orders linked to inventory counts for a specific
        month<br />Scope for public applications : read_inventory'
      operationId: api.inventory_counts.stock_orders.index
  "/stock_transfer/":
    get:
      tags:
      - products
      - stock_transfer
      summary: Returns stock transfers
      description: 'Returns stock transfers<br />Scope for public applications : read_inventory<br
        />Results per page : 250'
      operationId: api.stock_transfer.index
    post:
      tags:
      - products
      - stock_transfer
      summary: Create a stock transfer
      description: 'Create a stock transfer<br />Scope for public applications : write_inventory'
      operationId: api.stock_transfer.add
  "/stock_transfer/{transfer_id}":
    get:
      tags:
      - products
      - stock_transfer
      summary: Returns details of a stock transfer
      description: 'Returns details of a stock transfer<br />Scope for public applications
        : read_inventory'
      operationId: api.stock_transfer_info.index
  "/stock_transfer_validate/":
    post:
      tags:
      - products
      - stock_transfer
      summary: Validate a stock transfer
      description: 'Validate a stock transfer<br />Scope for public applications :
        write_inventory'
      operationId: api.stock_transfer_validate.add
  "/stock_transfer_details/{transfer_id}":
    get:
      tags:
      - products
      - stock_transfer
      summary: Returns details of a stock transfer
      description: 'Returns details of a stock transfer<br />Scope for public applications
        : read_inventory'
      operationId: api.stock_transfer_details.index
    post:
      tags:
      - products
      - stock_transfer
      summary: Add a product to a specific transfer_id
      description: 'Add a product to a specific transfer_id<br />Scope for public
        applications : write_inventory'
      operationId: api.stock_transfer_details.add_product
  "/stock_transfer_details/{stock_transfer_detail_id}":
    delete:
      tags:
      - products
      - stock_transfer
      summary: Delete a stock_transfer_detail_id
      description: 'Delete a stock_transfer_detail_id<br />Scope for public applications
        : write_inventory'
      operationId: api.stock_transfer_details.delete
  "/stock_transfer_on_hold/":
    get:
      tags:
      - products
      - stock_transfer
      summary: Returns the list of stock transfer details on hold
      description: 'Returns the list of stock transfer details on hold<br />Scope
        for public applications : read_inventory<br />Results per page : 250'
      operationId: api.stock_transfer_details_on_hold.index
  "/stores":
    get:
      tags:
      - stores
      summary: Returns stores by ID
      description: 'Returns stores by ID<br />Scope for public applications : read_settings'
      operationId: api.stores.index
  "/subscriptions":
    get:
      tags:
      - subscriptions
      summary: Returns subscriptions
      description: 'Returns subscriptions<br />Scope for public applications : read_settings'
      operationId: api.subscriptions.get
  "/suppliers/":
    get:
      tags:
      - suppliers
      summary: Returns suppliers by ID
      description: 'Returns suppliers by ID<br />Scope for public applications : read
        products'
      operationId: api.suppliers.index
    put:
      tags:
      - suppliers
      summary: Update a supplier
      description: 'Update a supplier<br />Scope for public applications : write_products'
      operationId: api.suppliers.update
    post:
      tags:
      - suppliers
      summary: Create a new supplier
      description: 'Create a new supplier<br />Scope for public applications : write_products'
      operationId: api.suppliers.add
  "/suppliers/{supplier_id}":
    delete:
      tags:
      - suppliers
      summary: Delete a supplier
      description: 'Delete a supplier. All products with the deleted supplier will
        loose the information. Same for statistics for this supplier.<br />Scope for
        public applications : write_products'
      operationId: api.suppliers.delete
  "/taxes":
    get:
      tags:
      - taxes
      summary: Returns taxes by ID
      description: 'Returns taxes by ID<br />Scope for public applications : read_settings'
      operationId: api.taxes.index
  "/till/{store_id}/{year}/{month}":
    get:
      tags:
      - till
      summary: Returns cash movements for a store_id for a specific month
      description: 'Returns cash movements for a store_id for a specific month<br
        />Scope for public applications : read_reports'
      operationId: api.till.index
  "/till/cash_in":
    post:
      tags:
      - till
      summary: Add cash to your till
      description: 'Add cash to your till (aside from your sales payments) such as
        your cash float or additional money<br />Scope for public applications : write_reports'
      operationId: api.till.cash_in
  "/till/cash_out":
    post:
      tags:
      - till
      summary: Remove cash from your till
      description: 'Remove cash from your till (aside from change on cash payments)
        such as safe drops or store expenses<br />Scope for public applications :
        write_reports'
      operationId: api.till.cash_out
  "/time_tracking/check_in":
    post:
      tags:
      - time_tracking
      summary: Check in a unique card_id
      description: 'Check in a unique card_id<br />Scope for public applications :
        write_time_tracking'
      operationId: api.time_tracking.check_in
  "/time_tracking/check_out":
    post:
      tags:
      - time_tracking
      summary: Check out a unique card_id
      description: 'Check out a unique card_id<br />Scope for public applications
        : write_time_tracking'
      operationId: api.time_tracking.check_out
  "/time_tracking/{time_tracking_id}/":
    get:
      tags:
      - time_tracking
      summary: Returns time_tracking_id details
      description: 'Returns time_tracking_id details<br />Scope for public applications
        : read_time_tracking'
      operationId: api.time_tracking.index
    put:
      tags:
      - time_tracking
      summary: Update a time_tracking id
      description: 'Update a time_tracking id<br />Scope for public applications :
        write_time_tracking'
      operationId: api.time_tracking.update
  "/time_tracking_date/{store_id}/{year}/{month}/{day}/":
    get:
      tags:
      - time_tracking
      summary: Returns time_tracking details for store_id for a specific day
      description: 'Returns time_tracking details for store_id for a specific day<br
        />Scope for public applications : read_time_tracking'
      operationId: api.time_tracking_date.index
  "/time_tracking_sale/{sale_id}/":
    get:
      tags:
      - time_tracking
      summary: Returns time_tracking_id details for a given sale_id
      description: 'Returns time_tracking_id details for a given sale_id<br />Scope
        for public applications : read_time_tracking'
      operationId: api.time_tracking_sale.index
  "/customers_time_tracking/{customer_id}/":
    get:
      tags:
      - time_tracking
      summary: Returns time_tracking for a specific customer_id
      description: 'Returns time_tracking for a specific customer_id<br />Scope for
        public applications : read_time_tracking'
      operationId: api.customers_time_tracking.index
  "/users":
    get:
      tags:
      - users
      summary: Returns users by ID
      description: 'Returns users by ID<br />Scope for public applications : no access'
      operationId: api.users.index
  "/user/password":
    put:
      tags:
      - users
      summary: Update a user's password
      description: 'Update a user''s password<br />Scope for public applications :
        no access'
      operationId: api.user.update_password
  "/warehouses":
    get:
      tags:
      - warehouses
      summary: Returns warehouses by ID
      description: 'Returns warehouses by ID<br />Scope for public applications :
        read_settings'
      operationId: api.warehouses.index
  "/webhooks":
    get:
      tags:
      - webhooks
      summary: Returns webhooks
      description: 'Returns webhooks<br />Scope for public applications : none'
      operationId: api.webhooks.get
  "/webhooks/":
    post:
      tags:
      - webhooks
      summary: Add a webhook
      description: 'Add a webhook<br />Scope for public applications : none'
      operationId: api.webhooks.add
  "/webhooks/{webhook_id}":
    delete:
      tags:
      - webhooks
      summary: Delete a webhook
      description: 'Delete a webhook<br />Scope for public applications : none'
      operationId: api.webhooks.delete
  "/z/payment_types/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns sales payments for store_id for a specific day
      description: 'Returns sales payments for store_id for a specific day<br />Scope
        for public applications : read_reports'
      operationId: api.z.payment_types.index
  "/z/payments_received/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns payments received for store_id for a specific day
      description: 'Returns payments received for store_id for a specific day<br />Scope
        for public applications : read_reports'
      operationId: api.z.payments_received.index
  "/z/customers_credit_deposits/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns customers credit deposits for store_id for a specific day
      description: 'Returns customers credit deposits for store_id for a specific
        day<br />Scope for public applications : read_reports'
      operationId: api.z.customers_credit_deposits.index
  "/z/customers/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns customers sales for store_id for a specific day
      description: 'Returns customers sales for store_id for a specific day<br />Scope
        for public applications : read_reports'
      operationId: api.z.customers.index
  "/z/taxes/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns sales taxes for store_id for a specific day
      description: 'Returns sales taxes for store_id for a specific day<br />Scope
        for public applications : read_reports'
      operationId: api.z.taxes.index
  "/z/categories/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns categories statistics for store_id for a specific day
      description: 'Returns categories statistics for store_id for a specific day<br
        />Scope for public applications : read_reports'
      operationId: api.z.categories.index
  "/z/accounting_accounts/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns accounting_accounts statistics for store_id for a specific
        day
      description: 'Returns accounting_accounts statistics for store_id for a specific
        day<br />Scope for public applications : read_reports'
      operationId: api.z.accounting_accounts.index
  "/z/date/":
    put:
      tags:
      - z
      - sales
      summary: Update the end-of-day date for a sale_id
      description: 'Update the end-of-day date for a sale_id<br />Scope for public
        applications : write_reports'
      operationId: api.z.update_date_z
  "/z/closure/{store_id}/{year}/{month}/{day}":
    post:
      tags:
      - z
      summary: Close the day and previous days
      description: 'Close the day and previous days<br />Scope for public applications
        : forbidden'
      operationId: api.z.closure.add
  "/z/cash_book/{store_id}/{year}/{month}/{day}":
    get:
      tags:
      - z
      summary: Returns cash book movements for store_id for a specific day or month
      description: 'Returns cash book movements for store_id for a specific day or
        month <br />Scope for public applications : read_reports<br />Results per
        page : 250'
      operationId: api.z.cash_book.index