name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    name: Deploy API documentations on Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: ./.github/scripts/deploy-all.sh
        env:
          AMADEUS_BUMP_TOKEN: ${{ secrets.AMADEUS_BUMP_TOKEN }}
          CLEVER_CLOUD_BUMP_TOKEN: ${{ secrets.CLEVER_CLOUD_BUMP_TOKEN }}
          EXAMPLES_BUMP_TOKEN: ${{ secrets.EXAMPLES_BUMP_TOKEN }}
          INTERCOM_BUMP_TOKEN: ${{ secrets.INTERCOM_BUMP_TOKEN }}
          MY_TRAIN_COMPANY_BUMP_TOKEN: ${{ secrets.MY_TRAIN_COMPANY_BUMP_TOKEN }}
          SCALEWAY_DEVELOPERS_BUMP_TOKEN: ${{ secrets.SCALEWAY_DEVELOPERS_BUMP_TOKEN }}
          TWITTER_API_V2_BUMP_TOKEN: ${{ secrets.TWITTER_API_V2_BUMP_TOKEN }}
          ZBOS_MQTT_BUMP_TOKEN: ${{ secrets.ZBOS_MQTT_BUMP_TOKEN }}
          PAYFIT_PARTNER_API_BUMP_TOKEN: ${{ secrets.PAYFIT_PARTNER_API_BUMP_TOKEN }}
          BUMP_HOST: ${{ secrets.BUMP_HOST }}
          GREENLY_BUMP_TOKEN: ${{ secrets.GREENLY_BUMP_TOKEN }}
          PIPEDRIVE_BUMP_TOKEN:  ${{ secrets.PIPEDRIVE_BUMP_TOKEN }}
