name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    name: Deploy API documentations on Bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: ./.github/scripts/deploy-all.sh
        env:
          AMADEUS_BUMP_TOKEN: ${{ secrets.AMADEUS_BUMP_TOKEN }}
          CLEVER_CLOUD_BUMP_TOKEN: ${{ secrets.CLEVER_CLOUD_BUMP_TOKEN }}
          EXAMPLES_BUMP_TOKEN: ${{ secrets.EXAMPLES_BUMP_TOKEN }}
          INTERCOM_BUMP_TOKEN: ${{ secrets.INTERCOM_BUMP_TOKEN }}
          MY_TRAIN_COMPANY_BUMP_TOKEN: ${{ secrets.MY_TRAIN_COMPANY_BUMP_TOKEN }}
          SCALEWAY_DEVELOPERS_BUMP_TOKEN: ${{ secrets.SCALEWAY_DEVELOPERS_BUMP_TOKEN }}
          TWITTER_API_V2_BUMP_TOKEN: ${{ secrets.TWITTER_API_V2_BUMP_TOKEN }}
          ZBOS_MQTT_BUMP_TOKEN: ${{ secrets.ZBOS_MQTT_BUMP_TOKEN }}
          PAYFIT_PARTNER_API_BUMP_TOKEN: ${{ secrets.PAYFIT_PARTNER_API_BUMP_TOKEN }}
          BUMP_HOST: ${{ secrets.BUMP_HOST }}
          GREENLY_BUMP_TOKEN: ${{ secrets.GREENLY_BUMP_TOKEN }}
          PIPEDRIVE_BUMP_TOKEN:  ${{ secrets.PIPEDRIVE_BUMP_TOKEN }}
          GITLAB_BUMP_TOKEN: ${{ secrets.GITLAB_BUMP_TOKEN }}
          REALWORLD_BUMP_TOKEN: ${{ secrets.REALWORLD_BUMP_TOKEN }}
          ASI_BUMP_TOKEN: ${{ secrets.ASI_BUMP_TOKEN }}
          AXONAUT_BUMP_TOKEN: ${{ secrets.AXONAUT_BUMP_TOKEN }}
          FAIRJUNGLE_BUMP_TOKEN: ${{ secrets.FAIRJUNGLE_BUMP_TOKEN }}
          GALISE_BUMP_TOKEN: ${{ secrets.GALISE_BUMP_TOKEN }}
          GITGUARDIAN_BUMP_TOKEN: ${{ secrets.GITGUARDIAN_BUMP_TOKEN }}
          HIBOUTIK_BUMP_TOKEN: ${{ secrets.HIBOUTIK_BUMP_TOKEN }}
          INPI_API_RNCS_BUMP_TOKEN: ${{ secrets.INPI_API_RNCS_BUMP_TOKEN }}
          LUMAPPS_BUMP_TOKEN: ${{ secrets.LUMAPPS_BUMP_TOKEN }}
          MAPOTEMPO_BUMP_TOKEN: ${{ secrets.MAPOTEMPO_BUMP_TOKEN }}
          NEXTAUTH_BUMP_TOKEN: ${{ secrets.NEXTAUTH_BUMP_TOKEN }}
          PAPPERS_BUMP_TOKEN: ${{ secrets.PAPPERS_BUMP_TOKEN }}
          PAYGREEN_BUMP_TOKEN: ${{ secrets.PAYGREEN_BUMP_TOKEN }}
          REMOVE_BG_BUMP_TOKEN: ${{ secrets.REMOVE_BG_BUMP_TOKEN }}
          RESTAURANTS_API_BUMP_TOKEN: ${{ secrets.RESTAURANTS_API_BUMP_TOKEN }}
          SKALEET_BUMP_TOKEN: ${{ secrets.SKALEET_BUMP_TOKEN }}
          SLACK_API_BUMP_TOKEN: ${{ secrets.SLACK_API_BUMP_TOKEN }}
          TALEEZ_BUMP_TOKEN: ${{ secrets.TALEEZ_BUMP_TOKEN }}
          AMAZON_BUMP_TOKEN: ${{ secrets.AMAZON_BUMP_TOKEN }}
          GRAVITEE_BUMP_TOKEN: ${{ secrets.GRAVITEE_BUMP_TOKEN }}
          IGN_BUMP_TOKEN: ${{ secrets.IGN_BUMP_TOKEN }}
          TIC_TAC_TOE_BUMP_TOKEN: ${{ secrets.TIC_TAC_TOE_BUMP_TOKEN }}
