name: API diff on Pull Requests

on:
  pull_request_target:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  realworld-api-diff:
    name: Check public Realworld API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          file: apis/realworld-openapi-source.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  gitlab-api-diff:
    name: Check public Gitlab API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          file: apis/gitlab-openapi-source.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  greenly-api-diff:
    name: Check Greenly API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Apply overlay to API document
        run: |
          npx bump-cli overlay apis/greenly-openapi-source.json overlays/greenly-remove-operation.yaml > tmp/greenly-openapi-public.json
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: greenly
          token: ${{ secrets.GREENLY_BUMP_TOKEN }}
          file: tmp/greenly-openapi-public.json
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
